### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Fireboyd78** [TheBerkin/Docpal#1]
Very interesting concept you have going on here, I wanted to try it out myself but unfortunately I didn't see any requirements about Visual Studio 2017. The solution file says the minimum version can be 2010 (or is it 2012?) but in actuality it's restricted to VS 2017/C# 7.0 -- I haven't made the upgrade to either of these yet as none of my own projects require them, but I am kind of disappointed I'm not able to try it out.

I'd personally suggest either dropping the over-reliance on `out <type> <name>` variables, or making it clear that the newer Visual Studio is required and editing the readme and solution files as necessary.

**Comment by TheBerkin** [comment]
I'll be sure to edit the Readme to clarify the VS version required. Sorry for the confusion.

I've also set up an automated build on appveyor so you don't have to compile it yourself:
https://ci.appveyor.com/project/TheBerkin/docpal/build/artifacts
